### ISSUE TITLE
Не деплоится

### ISSUE THREAD

**Issue by DamirHanov** [Maxsior/BotCom#11]
При мердже на стадии деплоя из-за чего-то не запускается дета
![image](https://user-images.githubusercontent.com/46625865/100736380-74d3b380-33f4-11eb-80eb-4e3a157e394c.png)

Кажется, что он запускает не оттуда, откуда надо

**Comment by Maxsior** [comment]
Там происходит установка Deta CLI, а после неё нужно перезапустить терминал. Надо, наверное, запустить в отдельном джобе деплой, и тогда это будет равносильно открутию нового терминала.
Сейчас проверю
